version: '3.3'

services:
  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "theVault:/shared"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
  nginx:
    depends_on:
      - php-fpm
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "theVault:/shared"
    restart: always

volumes:
  theVault:
    driver: local 
